spring.application.name=demo

spring.ai.openai.api-key=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

spring.ai.openai.chat.model=gpt-4o-mini
